package admin

import (
	"context"
	"database/sql"
	"math"
	"time"

	"github.com/theinventorylib/aegis/core"
	"github.com/theinventorylib/aegis/plugins/admin/internal/gen/sqlc"
)

// DefaultAdminStore implements AdminStore using a SQL database.
//
// This implementation uses sqlc-generated type-safe queries to manage users
// with admin-specific fields (role, ban status) in PostgreSQL, MySQL, or SQLite.
//
// Database Schema Extensions:
// Adds columns to the 'user' table:
//   - role (VARCHAR): User role for RBAC
//   - banned (BOOLEAN): Ban status
//   - ban_reason (TEXT): Ban reason description
//   - ban_expiry (TIMESTAMP, nullable): Ban expiration date
//   - ban_counter (INTEGER): Number of bans (repeat offender tracking)
//
// Thread Safety:
// Safe for concurrent use through database transactions.
type DefaultAdminStore struct {
	// q provides type-safe SQL queries generated by sqlc.
	// Queries are defined in internal/sql/<dialect>/query.sql.
	q *sqlc.Queries
}

// NewDefaultAdminStore creates a new DefaultAdminStore backed by SQL.
//
// The provided database connection must have the admin schema extensions applied.
//
// Parameters:
//   - db: Active SQL database connection
//
// Returns:
//   - *DefaultAdminStore: Configured store ready for use
func NewDefaultAdminStore(db *sql.DB) *DefaultAdminStore {
	return &DefaultAdminStore{
		q: sqlc.New(db),
	}
}

// UserStore implementation

// Create creates a new user.
func (s *DefaultAdminStore) Create(ctx context.Context, user User) (User, error) {
	params := sqlc.CreateUserParams{
		ID:        user.ID,
		Avatar:    toNullString(user.Avatar),
		Name:      user.Name,
		Email:     toNullString(user.Email),
		CreatedAt: user.CreatedAt.Format(time.RFC3339),
		UpdatedAt: user.UpdatedAt.Format(time.RFC3339),
		Disabled:  boolToInt(user.Disabled),
		Role:      toNullString(user.Role),
	}
	err := s.q.CreateUser(ctx, params)
	if err != nil {
		return User{}, err
	}
	return user, nil
}

// GetByEmail retrieves a user by email.
func (s *DefaultAdminStore) GetByEmail(ctx context.Context, email string) (User, error) {
	u, err := s.q.GetUserByEmail(ctx, toNullString(email))
	if err != nil {
		return User{}, err
	}
	return sqlcUserToUser(u), nil
}

// GetByID retrieves a user by ID.
func (s *DefaultAdminStore) GetByID(ctx context.Context, id string) (User, error) {
	u, err := s.q.GetUserByID(ctx, id)
	if err != nil {
		return User{}, err
	}
	return sqlcUserToUser(u), nil
}

// Update updates user information.
func (s *DefaultAdminStore) Update(ctx context.Context, user User) error {
	params := sqlc.UpdateUserParams{
		ID:        user.ID,
		Avatar:    toNullString(user.Avatar),
		Name:      user.Name,
		Email:     toNullString(user.Email),
		UpdatedAt: user.UpdatedAt.Format(time.RFC3339),
		Disabled:  boolToInt(user.Disabled),
		// We don't update role here; use UpdateUserRole
	}
	return s.q.UpdateUser(ctx, params)
}

// Delete removes a user.
func (s *DefaultAdminStore) Delete(ctx context.Context, id string) error {
	return s.q.DeleteUser(ctx, sqlc.DeleteUserParams{
		ID:        id,
		UpdatedAt: time.Now().Format(time.RFC3339),
	})
}

// List retrieves a paginated list of users.
func (s *DefaultAdminStore) List(ctx context.Context, offset, limit int) ([]User, error) {
	// Handle pagination with safe int32 conversion (G115)
	if offset < 0 {
		offset = 0
	}
	if limit <= 0 {
		limit = 10
	}
	// Ensure values are within int32 range
	if offset > math.MaxInt32 {
		offset = math.MaxInt32
	}
	if limit > math.MaxInt32 {
		limit = math.MaxInt32
	}
	params := sqlc.ListUsersParams{
		Offset: core.ClampIntToInt32(offset), // safe clamp to int32
		Limit:  core.ClampIntToInt32(limit),  // safe clamp to int32
	}
	users, err := s.q.ListUsers(ctx, params)
	if err != nil {
		return nil, err
	}
	result := make([]User, len(users))
	for i, u := range users {
		result[i] = sqlcUserToUser(u)
	}
	return result, nil
}

// Count returns the total number of users.
func (s *DefaultAdminStore) Count(ctx context.Context) (int, error) {
	count, err := s.q.CountUsers(ctx)
	return int(count), err
}

// AdminStore additional methods

// AssignRole assigns a role to a user.
func (s *DefaultAdminStore) AssignRole(ctx context.Context, userID string, role string) error {
	return s.q.UpdateUserRole(ctx, sqlc.UpdateUserRoleParams{
		ID:        userID,
		Role:      toNullString(role),
		UpdatedAt: time.Now().Format(time.RFC3339),
	})
}

// GetRole retrieves a user's role.
func (s *DefaultAdminStore) GetRole(ctx context.Context, userID string) (string, error) {
	role, err := s.q.GetRole(ctx, userID)
	if err != nil {
		return "", err
	}
	return role, nil
}

// RemoveRole removes a role from a user.
func (s *DefaultAdminStore) RemoveRole(ctx context.Context, userID string, _ string) error {
	// In this implementation, we just set role back to 'user'
	// We ignore the 'role' argument if we only support one role per user
	return s.AssignRole(ctx, userID, "user")
}

// ListUsersRaw lists users returning raw map data.
func (s *DefaultAdminStore) ListUsersRaw(ctx context.Context, offset, limit int) ([]map[string]interface{}, error) {
	// Ensure values are within int32 range
	if offset < 0 {
		offset = 0
	}
	if limit <= 0 {
		limit = 10
	}
	if offset > math.MaxInt32 {
		offset = math.MaxInt32
	}
	if limit > math.MaxInt32 {
		limit = math.MaxInt32
	}
	users, err := s.q.ListUsersRaw(ctx, sqlc.ListUsersRawParams{
		Offset: core.ClampIntToInt32(offset), // safe clamp to int32
		Limit:  core.ClampIntToInt32(limit),  // safe clamp to int32
	})
	if err != nil {
		return nil, err
	}
	result := make([]map[string]interface{}, len(users))
	for i, u := range users {
		result[i] = map[string]interface{}{
			"id":        u.ID,
			"createdAt": u.CreatedAt,
			"updatedAt": u.UpdatedAt,
			"email":     u.Email,
			"role":      u.Role,
			"disabled":  intToBool(u.Disabled),
		}
	}
	return result, nil
}

// GetUserRaw retrieves a single user as raw map data.
func (s *DefaultAdminStore) GetUserRaw(ctx context.Context, userID string) (map[string]interface{}, error) {
	u, err := s.q.GetUserRaw(ctx, userID)
	if err != nil {
		return nil, err
	}
	return map[string]interface{}{
		"id":        u.ID,
		"createdAt": u.CreatedAt,
		"updatedAt": u.UpdatedAt,
		"email":     u.Email,
		"role":      u.Role,
		"disabled":  intToBool(u.Disabled),
	}, nil
}

// BanUser bans a user.
func (s *DefaultAdminStore) BanUser(ctx context.Context, userID, reason string, expiry *time.Time) error {
	var expiryStr sql.NullString
	if expiry != nil {
		expiryStr = sql.NullString{String: expiry.Format(time.RFC3339), Valid: true}
	}
	return s.q.BanUser(ctx, sqlc.BanUserParams{
		ID:        userID,
		BanReason: toNullString(reason),
		BanExpiry: expiryStr,
		UpdatedAt: time.Now().Format(time.RFC3339),
	})
}

// UnbanUser unbans a user.
func (s *DefaultAdminStore) UnbanUser(ctx context.Context, userID string) error {
	return s.q.UnbanUser(ctx, sqlc.UnbanUserParams{
		ID:        userID,
		UpdatedAt: time.Now().Format(time.RFC3339),
	})
}

// GetStats retrieves system statistics.
func (s *DefaultAdminStore) GetStats(ctx context.Context) (StatsResponse, error) {
	count, err := s.q.CountUsers(ctx)
	if err != nil {
		return StatsResponse{}, err
	}
	return StatsResponse{
		TotalUsers: int(count),
	}, nil
}

// Helper functions

func sqlcUserToUser(u sqlc.User) User {
	createdAt, err := time.Parse(time.RFC3339, u.CreatedAt)
	_ = err
	updatedAt, err := time.Parse(time.RFC3339, u.UpdatedAt)
	_ = err
	var banExpiry *time.Time
	if u.BanExpiry.Valid {
		if t, err := time.Parse(time.RFC3339, u.BanExpiry.String); err == nil {
			banExpiry = &t
		}
	}
	user := User{}
	user.SetID(u.ID)
	user.Avatar = fromNullString(u.Avatar)
	user.SetName(u.Name)
	user.SetEmail(fromNullString(u.Email))
	user.SetCreatedAt(createdAt)
	user.SetUpdatedAt(updatedAt)
	user.Disabled = intToBool(u.Disabled)
	user.Role = fromNullString(u.Role)
	user.Banned = intToBool(u.Banned)
	user.BanReason = fromNullString(u.BanReason)
	user.BanExpiry = banExpiry
	user.BanCounter = int(u.BanCounter)
	return user
}

func toNullString(s string) sql.NullString {
	if s == "" {
		return sql.NullString{Valid: false}
	}
	return sql.NullString{String: s, Valid: true}
}

func fromNullString(ns sql.NullString) string {
	if ns.Valid {
		return ns.String
	}
	return ""
}

func boolToInt(b bool) int32 {
	if b {
		return 1
	}
	return 0
}

func intToBool(i int32) bool {
	return i != 0
}
