package organizations

import (
	"context"
	"database/sql"
	"time"

	"github.com/theinventorylib/aegis/plugins/organizations/internal/gen/sqlc"
)

// DefaultOrganizationStore implements OrganizationStore using a SQL database.
//
// This implementation uses sqlc-generated type-safe queries to manage organizations,
// members, teams, and team members in PostgreSQL, MySQL, or SQLite.
//
// Database Tables:
//   - organization: Organization metadata (id, name, slug)
//   - members: Organization membership with roles
//   - team: Team metadata within organizations
//   - team_member: Team membership with roles
//
// Constraints:
//   - organization.slug: UNIQUE (for URL routing)
//   - members(user_id, organization_id): UNIQUE (one membership per user per org)
//   - team_member(team_id, user_id): UNIQUE (one membership per user per team)
//   - Foreign keys with CASCADE DELETE for referential integrity
//
// Thread Safety:
// This store is safe for concurrent use through database transactions.
type DefaultOrganizationStore struct {
	// q provides type-safe SQL queries generated by sqlc.
	// Queries are defined in internal/sql/<dialect>/query.sql.
	q *sqlc.Queries
}

// NewDefaultOrganizationStore creates a new DefaultOrganizationStore backed by SQL.
//
// The provided database connection must have the organization schema applied.
//
// Parameters:
//   - db: Active SQL database connection
//
// Returns:
//   - *DefaultOrganizationStore: Configured store ready for use
func NewDefaultOrganizationStore(db *sql.DB) *DefaultOrganizationStore {
	return &DefaultOrganizationStore{
		q: sqlc.New(db),
	}
}

// Organization operations

func (s *DefaultOrganizationStore) CreateOrganization(ctx context.Context, id, name, slug string, createdAt, updatedAt time.Time) error {
	params := sqlc.CreateOrganizationParams{
		ID:        id,
		Name:      name,
		Slug:      slug,
		CreatedAt: createdAt.Format(time.RFC3339),
		UpdatedAt: updatedAt.Format(time.RFC3339),
	}
	return s.q.CreateOrganization(ctx, params)
}

func (s *DefaultOrganizationStore) GetOrganization(ctx context.Context, id string) (Organization, error) {
	o, err := s.q.GetOrganization(ctx, id)
	if err != nil {
		return Organization{}, err
	}
	return sqlcOrganizationToOrganization(o), nil
}

func (s *DefaultOrganizationStore) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	o, err := s.q.GetOrganizationBySlug(ctx, slug)
	if err != nil {
		return Organization{}, err
	}
	return sqlcOrganizationToOrganization(o), nil
}

func (s *DefaultOrganizationStore) UpdateOrganization(ctx context.Context, id, name, slug string, updatedAt time.Time) error {
	params := sqlc.UpdateOrganizationParams{
		ID:        id,
		Name:      name,
		Slug:      slug,
		UpdatedAt: updatedAt.Format(time.RFC3339),
	}
	return s.q.UpdateOrganization(ctx, params)
}

func (s *DefaultOrganizationStore) DeleteOrganization(ctx context.Context, id string, updatedAt time.Time) error {
	return s.q.DeleteOrganization(ctx, sqlc.DeleteOrganizationParams{
		ID:        id,
		UpdatedAt: updatedAt.Format(time.RFC3339),
	})
}

func (s *DefaultOrganizationStore) ListUserOrganizations(ctx context.Context, userID string) ([]Organization, error) {
	orgs, err := s.q.ListUserOrganizations(ctx, userID)
	if err != nil {
		return nil, err
	}
	result := make([]Organization, len(orgs))
	for i, o := range orgs {
		result[i] = sqlcOrganizationToOrganization(o)
	}
	return result, nil
}

// Member operations

func (s *DefaultOrganizationStore) CreateMember(ctx context.Context, id, userID, orgID, role string, createdAt, updatedAt time.Time) error {
	params := sqlc.CreateMemberParams{
		ID:             id,
		UserID:         userID,
		OrganizationID: orgID,
		Role:           role,
		CreatedAt:      createdAt.Format(time.RFC3339),
		UpdatedAt:      updatedAt.Format(time.RFC3339),
	}
	return s.q.CreateMember(ctx, params)
}

func (s *DefaultOrganizationStore) GetMember(ctx context.Context, userID, orgID string) (Member, error) {
	o, err := s.q.GetMember(ctx, sqlc.GetMemberParams{
		UserID:         userID,
		OrganizationID: orgID,
	})
	if err != nil {
		return Member{}, err
	}
	return sqlcMemberToMember(o), nil
}

func (s *DefaultOrganizationStore) IsOrganizationMember(ctx context.Context, userID, orgID string) (bool, error) {
	return s.q.IsOrganizationMember(ctx, sqlc.IsOrganizationMemberParams{
		UserID:         userID,
		OrganizationID: orgID,
	})
}

func (s *DefaultOrganizationStore) IsOwnerOrAdmin(ctx context.Context, userID, orgID string) (bool, error) {
	return s.q.IsOwnerOrAdmin(ctx, sqlc.IsOwnerOrAdminParams{
		UserID:         userID,
		OrganizationID: orgID,
	})
}

func (s *DefaultOrganizationStore) IsOwner(ctx context.Context, userID, orgID string) (bool, error) {
	return s.q.IsOwner(ctx, sqlc.IsOwnerParams{
		UserID:         userID,
		OrganizationID: orgID,
	})
}

func (s *DefaultOrganizationStore) UpdateMemberRole(ctx context.Context, userID, orgID, role string, updatedAt time.Time) error {
	return s.q.UpdateMemberRole(ctx, sqlc.UpdateMemberRoleParams{
		UserID:         userID,
		OrganizationID: orgID,
		Role:           role,
		UpdatedAt:      updatedAt.Format(time.RFC3339),
	})
}

func (s *DefaultOrganizationStore) RemoveMember(ctx context.Context, userID, orgID string) error {
	return s.q.RemoveMember(ctx, sqlc.RemoveMemberParams{
		UserID:         userID,
		OrganizationID: orgID,
	})
}

func (s *DefaultOrganizationStore) ListOrganizationMembers(ctx context.Context, orgID string) ([]Member, error) {
	members, err := s.q.ListOrganizationMembers(ctx, orgID)
	if err != nil {
		return nil, err
	}
	result := make([]Member, len(members))
	for i, m := range members {
		result[i] = sqlcMemberToMember(m)
	}
	return result, nil
}

// Team operations

func (s *DefaultOrganizationStore) CreateTeam(ctx context.Context, id, orgID, name, description string, createdAt, updatedAt time.Time) error {
	params := sqlc.CreateTeamParams{
		ID:             id,
		OrganizationID: orgID,
		Name:           name,
		Description:    sql.NullString{String: description, Valid: description != ""},
		CreatedAt:      createdAt.Format(time.RFC3339),
		UpdatedAt:      updatedAt.Format(time.RFC3339),
	}
	return s.q.CreateTeam(ctx, params)
}

func (s *DefaultOrganizationStore) GetTeam(ctx context.Context, id string) (Team, error) {
	t, err := s.q.GetTeam(ctx, id)
	if err != nil {
		return Team{}, err
	}
	return sqlcTeamToTeam(t), nil
}

func (s *DefaultOrganizationStore) ListTeams(ctx context.Context, orgID string) ([]Team, error) {
	teams, err := s.q.ListTeams(ctx, orgID)
	if err != nil {
		return nil, err
	}
	result := make([]Team, len(teams))
	for i, t := range teams {
		result[i] = sqlcTeamToTeam(t)
	}
	return result, nil
}

func (s *DefaultOrganizationStore) UpdateTeam(ctx context.Context, id, name, description string, updatedAt time.Time) error {
	params := sqlc.UpdateTeamParams{
		ID:          id,
		Name:        name,
		Description: sql.NullString{String: description, Valid: description != ""},
		UpdatedAt:   updatedAt.Format(time.RFC3339),
	}
	return s.q.UpdateTeam(ctx, params)
}

func (s *DefaultOrganizationStore) DeleteTeam(ctx context.Context, id string) error {
	return s.q.DeleteTeam(ctx, id)
}

// Team Member operations

func (s *DefaultOrganizationStore) CreateTeamMember(ctx context.Context, id, teamID, userID, role string, createdAt, updatedAt time.Time) error {
	params := sqlc.CreateTeamMemberParams{
		ID:        id,
		TeamID:    teamID,
		UserID:    userID,
		Role:      role,
		CreatedAt: createdAt.Format(time.RFC3339),
		UpdatedAt: updatedAt.Format(time.RFC3339),
	}
	return s.q.CreateTeamMember(ctx, params)
}

func (s *DefaultOrganizationStore) GetTeamMember(ctx context.Context, teamID, userID string) (TeamMember, error) {
	tm, err := s.q.GetTeamMember(ctx, sqlc.GetTeamMemberParams{
		TeamID: teamID,
		UserID: userID,
	})
	if err != nil {
		return TeamMember{}, err
	}
	return sqlcTeamMemberToTeamMember(tm), nil
}

func (s *DefaultOrganizationStore) ListTeamMembers(ctx context.Context, teamID string) ([]TeamMember, error) {
	members, err := s.q.ListTeamMembers(ctx, teamID)
	if err != nil {
		return nil, err
	}
	result := make([]TeamMember, len(members))
	for i, m := range members {
		result[i] = sqlcTeamMemberToTeamMember(m)
	}
	return result, nil
}

func (s *DefaultOrganizationStore) UpdateTeamMemberRole(ctx context.Context, teamID, userID, role string, updatedAt time.Time) error {
	return s.q.UpdateTeamMemberRole(ctx, sqlc.UpdateTeamMemberRoleParams{
		TeamID:    teamID,
		UserID:    userID,
		Role:      role,
		UpdatedAt: updatedAt.Format(time.RFC3339),
	})
}

func (s *DefaultOrganizationStore) RemoveTeamMember(ctx context.Context, teamID, userID string) error {
	return s.q.RemoveTeamMember(ctx, sqlc.RemoveTeamMemberParams{
		TeamID: teamID,
		UserID: userID,
	})
}

// Helper functions to convert sqlc types to our domain types

func sqlcOrganizationToOrganization(o interface{}) Organization {
	var id, name, slug, createdAt, updatedAt string
	switch v := o.(type) {
	case sqlc.GetOrganizationRow:
		id, name, slug, createdAt, updatedAt = v.ID, v.Name, v.Slug, v.CreatedAt, v.UpdatedAt
	case sqlc.GetOrganizationBySlugRow:
		id, name, slug, createdAt, updatedAt = v.ID, v.Name, v.Slug, v.CreatedAt, v.UpdatedAt
	case sqlc.ListUserOrganizationsRow:
		id, name, slug, createdAt, updatedAt = v.ID, v.Name, v.Slug, v.CreatedAt, v.UpdatedAt
	}
	createdAtTime, _ := time.Parse(time.RFC3339, createdAt)
	updatedAtTime, _ := time.Parse(time.RFC3339, updatedAt)
	return Organization{
		ID:        id,
		Name:      name,
		Slug:      slug,
		CreatedAt: createdAtTime,
		UpdatedAt: updatedAtTime,
	}
}

func sqlcMemberToMember(m sqlc.Member) Member {
	createdAt, _ := time.Parse(time.RFC3339, m.CreatedAt)
	updatedAt, _ := time.Parse(time.RFC3339, m.UpdatedAt)
	return Member{
		ID:             m.ID,
		UserID:         m.UserID,
		OrganizationID: m.OrganizationID,
		Role:           m.Role,
		CreatedAt:      createdAt,
		UpdatedAt:      updatedAt,
	}
}

func sqlcTeamToTeam(t sqlc.Team) Team {
	createdAt, _ := time.Parse(time.RFC3339, t.CreatedAt)
	updatedAt, _ := time.Parse(time.RFC3339, t.UpdatedAt)
	description := ""
	if t.Description.Valid {
		description = t.Description.String
	}
	return Team{
		ID:             t.ID,
		OrganizationID: t.OrganizationID,
		Name:           t.Name,
		Description:    description,
		CreatedAt:      createdAt,
		UpdatedAt:      updatedAt,
	}
}

func sqlcTeamMemberToTeamMember(m sqlc.TeamMember) TeamMember {
	createdAt, _ := time.Parse(time.RFC3339, m.CreatedAt)
	updatedAt, _ := time.Parse(time.RFC3339, m.UpdatedAt)
	return TeamMember{
		ID:        m.ID,
		TeamID:    m.TeamID,
		UserID:    m.UserID,
		Role:      m.Role,
		CreatedAt: createdAt,
		UpdatedAt: updatedAt,
	}
}
