package emailotp

import (
	"context"
	"database/sql"
	"time"

	"github.com/theinventorylib/aegis/auth"
	"github.com/theinventorylib/aegis/plugins/emailotp/internal/gen/sqlc"
)

// DefaultEmailOTPStore implements EmailOTPStore using a SQL database.
//
// This implementation uses sqlc-generated type-safe queries to manage users
// with email addresses in PostgreSQL, MySQL, or SQLite.
//
// Database Schema:
// Extends the 'user' table with:
//   - email (VARCHAR, unique): User email address
//   - email_verified (BOOLEAN): Email verification status
//
// Thread Safety:
// Safe for concurrent use through database transactions.
type DefaultEmailOTPStore struct {
	// q provides type-safe SQL queries generated by sqlc.
	// Queries are defined in internal/sql/<dialect>/query.sql.
	q *sqlc.Queries
}

// NewDefaultEmailOTPStore creates a new DefaultEmailOTPStore backed by SQL.
//
// The provided database connection must have the emailotp schema applied.
//
// Parameters:
//   - db: Active SQL database connection
//
// Returns:
//   - *DefaultEmailOTPStore: Configured store ready for use
func NewDefaultEmailOTPStore(db *sql.DB) *DefaultEmailOTPStore {
	return &DefaultEmailOTPStore{
		q: sqlc.New(db),
	}
}

// CreateUser creates a new user with email address.
func (s *DefaultEmailOTPStore) CreateUser(ctx context.Context, user User) (*User, error) {
	params := sqlc.CreateUserParams{
		ID:            user.ID,
		Avatar:        toNullString(user.Avatar),
		Name:          user.Name,
		Email:         toNullString(nullPointerString(user.Email)), // Handle email mapping
		CreatedAt:     user.CreatedAt.Format(time.RFC3339),
		UpdatedAt:     user.UpdatedAt.Format(time.RFC3339),
		Disabled:      boolToInt(user.Disabled),
		EmailVerified: boolToInt(user.EmailVerified),
	}

	if err := s.q.CreateUser(ctx, params); err != nil {
		return nil, err
	}

	return &user, nil
}

// GetUserByEmail retrieves a user by email address
func (s *DefaultEmailOTPStore) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	u, err := s.q.GetUserByEmail(ctx, toNullString(email))
	if err != nil {
		return nil, err
	}
	return sqlcUserToUser(u), nil
}

// UpdateUserEmail updates a user's email address and verification status
func (s *DefaultEmailOTPStore) UpdateUserEmail(ctx context.Context, userID, email string, verified bool) error {
	params := sqlc.UpdateUserEmailParams{
		ID:            userID,
		Email:         toNullString(email),
		EmailVerified: boolToInt(verified),
		UpdatedAt:     time.Now().Format(time.RFC3339),
	}
	return s.q.UpdateUserEmail(ctx, params)
}

func nullPointerString(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}

// Helper functions

func toNullString(s string) sql.NullString {
	if s == "" {
		return sql.NullString{Valid: false}
	}
	return sql.NullString{String: s, Valid: true}
}

func boolToInt(b bool) int32 {
	if b {
		return 1
	}
	return 0
}

func sqlcUserToUser(u sqlc.GetUserByEmailRow) *User {
	var email *string
	if u.Email.Valid {
		email = &u.Email.String
	}

	return &User{
		User: auth.User{
			ID:        u.ID,
			Avatar:    nullStringToString(u.Avatar),
			Name:      u.Name,
			Email:     nullStringToString(u.Email),
			CreatedAt: parseTime(u.CreatedAt),
			UpdatedAt: parseTime(u.UpdatedAt),
			Disabled:  u.Disabled != 0,
		},
		Email:         email,
		EmailVerified: u.EmailVerified != 0,
	}
}

func nullStringToString(ns sql.NullString) string {
	if ns.Valid {
		return ns.String
	}
	return ""
}

func parseTime(s string) time.Time {
	t, err := time.Parse(time.RFC3339, s)
	if err != nil {
		return time.Time{}
	}
	return t
}
