package sms

import (
	"context"
	"database/sql"
	"time"

	"github.com/theinventorylib/aegis/auth"
	"github.com/theinventorylib/aegis/plugins/sms/internal/gen/sqlc"
)

// DefaultSMSStore implements SMSStore using a SQL database.
//
// This implementation uses sqlc-generated type-safe queries to manage users
// with phone numbers in PostgreSQL, MySQL, or SQLite.
//
// Database Schema:
// Extends the 'user' table with:
//   - phone_number (VARCHAR, unique): User phone number in E.164 format
//   - phone_verified (BOOLEAN): Phone verification status
//
// Thread Safety:
// Safe for concurrent use through database transactions.
type DefaultSMSStore struct {
	// q provides type-safe SQL queries generated by sqlc.
	// Queries are defined in internal/sql/<dialect>/query.sql.
	q *sqlc.Queries
}

// NewDefaultSMSStore creates a new DefaultSMSStore backed by SQL.
//
// The provided database connection must have the SMS schema applied.
//
// Parameters:
//   - db: Active SQL database connection
//
// Returns:
//   - *DefaultSMSStore: Configured store ready for use
func NewDefaultSMSStore(db *sql.DB) *DefaultSMSStore {
	return &DefaultSMSStore{
		q: sqlc.New(db),
	}
}

// CreateUserWithPhone creates a new user with phone number
func (s *DefaultSMSStore) CreateUser(ctx context.Context, user User) (*User, error) {
	params := sqlc.CreateUserParams{
		ID:        user.ID,
		Avatar:    toNullString(user.Avatar),
		Name:      user.Name,
		Email:     toNullString(user.Email),
		CreatedAt: user.CreatedAt.Format(time.RFC3339),
		UpdatedAt: user.UpdatedAt.Format(time.RFC3339),
		Disabled:  boolToInt(user.Disabled),
	}
	err := s.q.CreateUser(ctx, params)
	if err != nil {
		return nil, err
	}
	return &user, nil
}

// GetUserByPhone retrieves a user by phone number
func (s *DefaultSMSStore) GetUserByPhone(ctx context.Context, phone string) (*User, error) {
	u, err := s.q.GetUserByPhone(ctx, toNullString(phone))
	if err != nil {
		return nil, err
	}
	return sqlcUserToUser(u), nil
}

// UpdateUserPhone updates a user's phone number and verification status
func (s *DefaultSMSStore) UpdateUserPhone(ctx context.Context, userID, phone string, verified bool) error {
	params := sqlc.UpdateUserPhoneParams{
		ID:            userID,
		PhoneNumber:   toNullString(phone),
		PhoneVerified: boolToInt(verified),
		UpdatedAt:     time.Now().Format(time.RFC3339),
	}
	return s.q.UpdateUserPhone(ctx, params)
}

// Helper functions

func toNullString(s string) sql.NullString {
	if s == "" {
		return sql.NullString{Valid: false}
	}
	return sql.NullString{String: s, Valid: true}
}

func boolToInt(b bool) int32 {
	if b {
		return 1
	}
	return 0
}

func sqlcUserToUser(u sqlc.User) *User {
	var phone *string
	if u.PhoneNumber.Valid {
		phone = &u.PhoneNumber.String
	}

	return &User{
		User: auth.User{
			ID:        u.ID,
			Avatar:    nullStringToString(u.Avatar),
			Name:      u.Name,
			Email:     nullStringToString(u.Email),
			CreatedAt: parseTime(u.CreatedAt),
			UpdatedAt: parseTime(u.UpdatedAt),
			Disabled:  u.Disabled != 0,
		},
		Phone:         phone,
		PhoneVerified: u.PhoneVerified != 0,
	}
}

func nullStringToString(ns sql.NullString) string {
	if ns.Valid {
		return ns.String
	}
	return ""
}

func parseTime(s string) time.Time {
	t, err := time.Parse(time.RFC3339, s)
	if err != nil {
		return time.Time{}
	}
	return t
}
