package jwt

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/lestrrat-go/jwx/v3/jwk"
	"github.com/theinventorylib/aegis/plugins/jwt/internal/gen/sqlc"
)

// DefaultJWTStore implements JWTStore using a SQL database backend.
//
// This implementation uses sqlc-generated type-safe queries to manage JWK storage
// in PostgreSQL, MySQL, or SQLite. It stores JWKs as JSON-serialized data in the
// jwks table, indexed by key ID (kid), algorithm, and use type.
//
// Database Schema:
//   - kid: Unique key identifier (matches JWT "kid" claim)
//   - key_data: JSON-serialized JWK (includes public and private key material)
//   - algorithm: Signing algorithm (e.g., "RS256", "ES256")
//   - use: Key usage ("sig" for signatures, "enc" for encryption)
//   - created_at: Timestamp when key was stored
//   - expires_at: Optional expiration timestamp for key rotation
//
// Thread Safety:
// This store is safe for concurrent use through database transactions.
// Multiple processes can share the same database without coordination.
//
// Example Usage:
//
//	db, _ := sql.Open("postgres", "postgresql://localhost/aegis")
//	store := NewDefaultJWTStore(db)
//
//	// Retrieve current signing key
//	key, err := store.GetCurrentJWK(ctx, "RS256", "sig")
//
//	// Store new key with expiration
//	expiry := time.Now().Add(30 * 24 * time.Hour)
//	err = store.StoreJWK(ctx, newKey, "RS256", "sig", &expiry)
//
//	// Clean up expired keys
//	err = store.DeleteExpiredJWKS(ctx)
type DefaultJWTStore struct {
	// q provides type-safe SQL queries generated by sqlc.
	// Queries are defined in internal/sql/<dialect>/query.sql.
	q *sqlc.Queries
}

// NewDefaultJWTStore creates a new DefaultJWTStore backed by a SQL database.
//
// The provided database connection must be configured for the correct dialect
// (PostgreSQL, MySQL, or SQLite) and have the jwks table schema applied.
//
// Parameters:
//   - db: Active SQL database connection (must have jwks table)
//
// Returns:
//   - Configured DefaultJWTStore ready for use
//
// Example:
//
//	db, _ := sql.Open("postgres", "postgresql://localhost/aegis")
//	store := NewDefaultJWTStore(db)
func NewDefaultJWTStore(db *sql.DB) *DefaultJWTStore {
	return &DefaultJWTStore{
		q: sqlc.New(db),
	}
}

// GetCurrentJWK retrieves the most recent non-expired JWK from the database
// matching the specified algorithm and use type.
//
// This method queries for the newest key (by created_at DESC) that:
//   - Matches the specified algorithm (e.g., "RS256")
//   - Matches the use type ("sig" for signing, "enc" for encryption)
//   - Is not expired (expires_at > NOW() OR expires_at IS NULL)
//
// The returned key includes both public and private key material for signing.
// For public-only keys (verification), use ListJWKS and extract PublicKey().
//
// Parameters:
//   - ctx: Request context (supports cancellation)
//   - algorithm: Key algorithm (e.g., "RS256", "ES256")
//   - use: Key usage ("sig" for signatures, "enc" for encryption)
//
// Returns:
//   - jwk.Key: Parsed JWK with public and private key material
//   - error: Database error, parsing error, or ErrNoRows if no key found
//
// Example:
//
//	// Get current RSA signing key
//	key, err := store.GetCurrentJWK(ctx, "RS256", "sig")
//	if err != nil {
//	    log.Fatal("No signing key available")
//	}
func (s *DefaultJWTStore) GetCurrentJWK(ctx context.Context, algorithm, use string) (jwk.Key, error) {
	keyData, err := s.q.GetCurrentJWK(ctx, sqlc.GetCurrentJWKParams{
		Algorithm: algorithm,
		Use:       sql.NullString{String: use, Valid: true},
	})
	if err != nil {
		return nil, err
	}

	return jwk.ParseKey([]byte(keyData))
}

// StoreJWK persists a JWK to the database with optional expiration.
//
// The key is JSON-serialized and stored with metadata for retrieval by
// algorithm and use type. This method is used during key rotation to add
// new keys while old keys remain valid until expiration.
//
// Key Storage:
//   - Extracts kid (key ID) from the JWK (must be set before calling)
//   - Serializes entire key (public + private) to JSON
//   - Stores with algorithm and use metadata for filtering
//   - Records creation timestamp for ordering (newest = current)
//   - Optional expiration timestamp for key rotation cleanup
//
// Key Rotation Workflow:
//  1. Generate new key with unique kid
//  2. Store with expiration = now + retention period
//  3. Old keys remain valid until expiration (token verification)
//  4. DeleteExpiredJWKS() removes old keys after retention period
//
// Parameters:
//   - ctx: Request context
//   - key: JWK to store (must have kid set via SetKeyID)
//   - algorithm: Signing algorithm (e.g., "RS256")
//   - use: Key usage ("sig" or "enc")
//   - expiresAt: Optional expiration (nil = never expires)
//
// Returns:
//   - error: Database error or JSON marshaling error
//
// Example:
//
//	key, _ := rsa.GenerateKey(rand.Reader, 2048)
//	jwkKey, _ := jwk.FromRaw(key)
//	jwkKey.SetKeyID("key-2024-01")
//	expiry := time.Now().Add(30 * 24 * time.Hour)
//	err := store.StoreJWK(ctx, jwkKey, "RS256", "sig", &expiry)
func (s *DefaultJWTStore) StoreJWK(ctx context.Context, key jwk.Key, algorithm, use string, expiresAt *time.Time) error {
	keyData, err := json.Marshal(key)
	if err != nil {
		return err
	}

	var expiresAtNull sql.NullTime
	if expiresAt != nil {
		expiresAtNull = sql.NullTime{Time: *expiresAt, Valid: true}
	}

	kid, _ := key.KeyID()
	now := time.Now()

	return s.q.StoreJWK(ctx, sqlc.StoreJWKParams{
		Kid:       kid,
		KeyData:   string(keyData),
		Algorithm: algorithm,
		Use:       sql.NullString{String: use, Valid: true},
		CreatedAt: now,
		ExpiresAt: expiresAtNull,
	})
}

// DeleteExpiredJWKS removes all expired keys from the database.
//
// This method should be called periodically (e.g., via background job) to clean up
// old keys after their retention period has passed. Keys are only deleted if:
//   - expires_at IS NOT NULL AND expires_at < NOW()
//
// Keys without expiration (expires_at = NULL) are never deleted automatically.
// This supports long-lived keys that don't rotate.
//
// Cleanup Strategy:
//   - Run on plugin initialization to remove stale keys from previous runs
//   - Schedule periodic cleanup (e.g., daily cron job)
//   - Safe to call frequently (only deletes expired keys)
//
// Returns:
//   - error: Database error if deletion fails
//
// Example:
//
//	// Clean up expired keys daily
//	go func() {
//	    ticker := time.NewTicker(24 * time.Hour)
//	    for range ticker.C {
//	        store.DeleteExpiredJWKS(context.Background())
//	    }
//	}()
func (s *DefaultJWTStore) DeleteExpiredJWKS(ctx context.Context) error {
	return s.q.DeleteExpiredJWKS(ctx)
}

// ListJWKS retrieves all non-expired JWKs from the database.
//
// This method returns keys that are currently valid for token verification:
//   - expires_at IS NULL (never expires), OR
//   - expires_at > NOW() (not yet expired)
//
// Used by the JWKS endpoint (/.well-known/jwks.json) to publish public keys
// for JWT verification by external services. The endpoint converts these to
// public-only keys before serving.
//
// Multiple Keys:
// During key rotation, multiple keys may be returned:
//   - New key: Recently created, used for signing new tokens
//   - Old keys: Still valid for verifying existing tokens
//
// Returns:
//   - []JWK: All current keys (private + public key material)
//   - error: Database query error
//
// Example:
//
//	// Serve JWKS endpoint
//	keys, _ := store.ListJWKS(ctx)
//	for _, dbKey := range keys {
//	    key, _ := jwk.ParseKey(dbKey.KeyData)
//	    pubKey, _ := key.PublicKey() // Extract public key only
//	    jwksSet.AddKey(pubKey)
//	}
func (s *DefaultJWTStore) ListJWKS(ctx context.Context) ([]JWK, error) {
	sqlcKeys, err := s.q.GetAllCurrentJWKS(ctx)
	if err != nil {
		return nil, err
	}

	keys := make([]JWK, len(sqlcKeys))
	for i, k := range sqlcKeys {
		var expiresAt *time.Time
		if k.ExpiresAt.Valid {
			expiresAt = &k.ExpiresAt.Time
		}
		keys[i] = JWK{
			Kid:       k.Kid,
			KeyData:   []byte(k.KeyData),
			Algorithm: k.Algorithm,
			Use:       k.Use.String,
			CreatedAt: k.CreatedAt,
			ExpiresAt: expiresAt,
		}
	}
	return keys, nil
}
