package oauth

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/theinventorylib/aegis/plugins/oauth/internal/gen/sqlc"
)

// DefaultOAuthStore implements OAuthStore using a SQL database backend.
//
// This implementation uses sqlc-generated type-safe queries to manage OAuth
// connections in PostgreSQL, MySQL, or SQLite. It stores connections in the
// oauth_connections table with foreign key constraints to auth.users.
//
// Database Table: oauth_connections
// Columns:
//   - id (TEXT PRIMARY KEY): Connection identifier
//   - user_id (TEXT NOT NULL): Foreign key to auth.users.id
//   - provider (TEXT NOT NULL): Provider name ("google", "github", etc.)
//   - provider_user_id (TEXT NOT NULL): Provider's user ID
//   - email, name, avatar_url: User profile from provider
//   - access_token, refresh_token: OAuth tokens
//   - expires_at: Token expiration timestamp
//   - provider_data (TEXT): JSON-encoded provider-specific fields
//   - created_at, updated_at: Timestamps
//
// Unique Constraint: (provider, provider_user_id)
// Foreign Key: user_id → auth.users.id ON DELETE CASCADE
type DefaultOAuthStore struct {
	// q provides type-safe SQL queries generated by sqlc.
	// Queries are defined in internal/sql/<dialect>/query.sql.
	q *sqlc.Queries
}

// NewDefaultOAuthStore creates a new DefaultOAuthStore backed by a SQL database.
//
// The provided database connection must be configured for the correct dialect
// and have the oauth_connections table schema applied.
//
// Parameters:
//   - db: Active SQL database connection
//
// Returns:
//   - *DefaultOAuthStore: Configured store ready for use
func NewDefaultOAuthStore(db *sql.DB) *DefaultOAuthStore {
	return &DefaultOAuthStore{
		q: sqlc.New(db),
	}
}

// CreateConnection creates a new OAuth connection
func (s *DefaultOAuthStore) CreateConnection(ctx context.Context, conn Connection) (*Connection, error) {
	providerData, err := json.Marshal(conn.ProviderData)
	if err != nil {
		return nil, err
	}
	params := sqlc.CreateConnectionParams{
		ID:             conn.ID,
		UserID:         conn.UserID,
		Provider:       conn.Provider,
		ProviderUserID: conn.ProviderUserID,
		Email:          toNullString(conn.Email),
		Name:           toNullString(conn.Name),
		AvatarUrl:      toNullString(conn.AvatarURL),
		AccessToken:    conn.AccessToken,
		RefreshToken:   toNullString(conn.RefreshToken),
		ExpiresAt:      conn.ExpiresAt.Format(time.RFC3339),
		ProviderData:   toNullString(string(providerData)),
		CreatedAt:      conn.CreatedAt.Format(time.RFC3339),
		UpdatedAt:      conn.UpdatedAt.Format(time.RFC3339),
	}
	err = s.q.CreateConnection(ctx, params)
	if err != nil {
		return nil, err
	}
	return &conn, nil
}

// GetConnectionByProviderUserID retrieves a connection by provider and provider user ID
func (s *DefaultOAuthStore) GetConnectionByProviderUserID(ctx context.Context, provider, providerUserID string) (*Connection, error) {
	conn, err := s.q.GetConnectionByProviderUserID(ctx, sqlc.GetConnectionByProviderUserIDParams{
		Provider:       provider,
		ProviderUserID: providerUserID,
	})
	if err != nil {
		return nil, err
	}
	return sqlcConnectionToConnection(conn), nil
}

// GetConnectionsByUserID retrieves all connections for a user
func (s *DefaultOAuthStore) GetConnectionsByUserID(ctx context.Context, userID string) ([]Connection, error) {
	conns, err := s.q.GetConnectionsByUserID(ctx, userID)
	if err != nil {
		return nil, err
	}
	var result []Connection
	for _, conn := range conns {
		result = append(result, *sqlcConnectionToConnection(conn))
	}
	return result, nil
}

// UpdateConnection updates an OAuth connection
func (s *DefaultOAuthStore) UpdateConnection(ctx context.Context, conn Connection) error {
	providerData, err := json.Marshal(conn.ProviderData)
	if err != nil {
		return err
	}
	params := sqlc.UpdateConnectionParams{
		ID:             conn.ID,
		UserID:         conn.UserID,
		Provider:       conn.Provider,
		ProviderUserID: conn.ProviderUserID,
		Email:          toNullString(conn.Email),
		Name:           toNullString(conn.Name),
		AvatarUrl:      toNullString(conn.AvatarURL),
		AccessToken:    conn.AccessToken,
		RefreshToken:   toNullString(conn.RefreshToken),
		ExpiresAt:      conn.ExpiresAt.Format(time.RFC3339),
		ProviderData:   toNullString(string(providerData)),
		UpdatedAt:      time.Now().Format(time.RFC3339),
	}
	return s.q.UpdateConnection(ctx, params)
}

// DeleteConnection deletes an OAuth connection by provider and user ID
func (s *DefaultOAuthStore) DeleteConnection(ctx context.Context, provider, userID string) error {
	return s.q.DeleteConnection(ctx, sqlc.DeleteConnectionParams{
		Provider: provider,
		UserID:   userID,
	})
}

// Helper functions

func toNullString(s string) sql.NullString {
	if s == "" {
		return sql.NullString{Valid: false}
	}
	return sql.NullString{String: s, Valid: true}
}

func sqlcConnectionToConnection(c sqlc.OauthConnection) *Connection {
	providerDataStr := nullStringToString(c.ProviderData)
	var providerData map[string]interface{}
	if providerDataStr != "" {
		if err := json.Unmarshal([]byte(providerDataStr), &providerData); err != nil {
			// If unmarshal fails, set to empty map
			providerData = make(map[string]interface{})
		}
	} else {
		providerData = make(map[string]interface{})
	}
	return &Connection{
		ID:             c.ID,
		UserID:         c.UserID,
		Provider:       c.Provider,
		ProviderUserID: c.ProviderUserID,
		Email:          nullStringToString(c.Email),
		Name:           nullStringToString(c.Name),
		AvatarURL:      nullStringToString(c.AvatarUrl),
		AccessToken:    c.AccessToken,
		RefreshToken:   nullStringToString(c.RefreshToken),
		ExpiresAt:      parseTime(c.ExpiresAt),
		ProviderData:   providerData,
		CreatedAt:      parseTime(c.CreatedAt),
		UpdatedAt:      parseTime(c.UpdatedAt),
	}
}

func nullStringToString(ns sql.NullString) string {
	if ns.Valid {
		return ns.String
	}
	return ""
}

func parseTime(s string) time.Time {
	t, err := time.Parse(time.RFC3339, s)
	if err != nil {
		return time.Time{}
	}
	return t
}
