package oauth

import (
	"time"

	"github.com/theinventorylib/aegis/auth"
)

// User represents an OAuth-authenticated user with provider tokens.
//
// This struct extends auth.User with OAuth-specific fields like access tokens
// and provider-specific data. It's used during the OAuth flow to transfer user
// information from the provider to Aegis.
//
// Fields:
//   - User: Base user fields (ID, Email, Name, Avatar from auth.User)
//   - AccessToken: OAuth access token for API calls to the provider
//   - RefreshToken: OAuth refresh token for renewing access tokens
//   - ExpiresAt: When the access token expires
//   - ProviderData: Provider-specific fields (e.g., Google's "locale", GitHub's "company")
type User struct {
	auth.User
	AccessToken  string
	RefreshToken string
	ExpiresAt    time.Time
	ProviderData map[string]interface{}
}

// Connection represents an OAuth connection stored in the database.
//
// This is the persistent storage model linking an Aegis user to an OAuth provider.
// Each connection stores the provider's user ID, tokens, and metadata for account
// linking and token refresh.
//
// Database Table: oauth_connections
// Primary Key: (provider, provider_user_id)
// Foreign Key: user_id → auth.users.id
//
// Example Row:
//   - ID: "conn_abc123"
//   - UserID: "user_xyz789"
//   - Provider: "google"
//   - ProviderUserID: "108234567890123456789" (Google's user ID)
//   - Email: "user@gmail.com"
//   - Name: "John Doe"
//   - AccessToken: "ya29.a0AfH6SMB..." (Google access token)
//   - RefreshToken: "1//0gZ..." (Google refresh token)
//   - ExpiresAt: 2024-01-01T13:00:00Z
type Connection struct {
	// Aegis fields
	ID        string    // Unique connection ID (generated by Aegis)
	UserID    string    // Aegis user ID (foreign key to auth.users)
	CreatedAt time.Time // When the connection was first created
	UpdatedAt time.Time // Last updated (token refresh, profile update)

	// OAuth provider fields
	Provider       string // Provider name ("google", "github", etc.)
	ProviderUserID string // Provider's user ID (Google: "108...", GitHub: "12345")

	// User profile from provider
	Email     string // User's email from provider
	Name      string // User's name from provider
	AvatarURL string // User's avatar URL from provider

	// OAuth tokens
	AccessToken  string    // OAuth access token for API calls
	RefreshToken string    // OAuth refresh token for renewing access
	ExpiresAt    time.Time // When the access token expires

	// Provider-specific data (JSON)
	ProviderData map[string]interface{} // Additional fields from provider
}

// ProviderConfig defines configuration for a single OAuth provider.
//
// This struct configures how Aegis integrates with an OAuth 2.0 or OpenID Connect
// provider. It supports both pre-built providers (Google, GitHub) and generic
// OAuth 2.0 providers with manual endpoint configuration.
//
// Pre-Built Providers:
// For well-known providers, only set ProviderType, ClientID, and ClientSecret:
//
//	{ProviderID: "google", ProviderType: "google", ClientID: "...", ClientSecret: "..."}
//
// Generic Providers:
// For custom OAuth providers, set endpoints manually or use DiscoveryURL:
//
//	{ProviderID: "custom", ProviderType: "generic", ClientID: "...", ClientSecret: "...",
//	 AuthURL: "https://provider.com/oauth/authorize",
//	 TokenURL: "https://provider.com/oauth/token",
//	 UserInfoURL: "https://provider.com/oauth/userinfo"}
type ProviderConfig struct {
	// Identity
	ProviderID   string // Unique ID (e.g., "google", "github", "line-jp")
	ProviderType string // Provider type (e.g., "google", "github", "generic")

	// OAuth Credentials
	ClientID     string // OAuth client ID from provider's developer console
	ClientSecret string // OAuth client secret from provider's developer console

	// OAuth Endpoints (for generic providers)
	AuthURL     string // Authorization endpoint
	TokenURL    string // Token endpoint
	UserInfoURL string // User info endpoint

	// Discovery (alternative to manual endpoints)
	DiscoveryURL string // OIDC discovery URL

	// OAuth Options
	Scopes      []string // OAuth scopes (e.g., ["email", "profile"])
	RedirectURI string   // Custom redirect URI (optional)

	// Advanced Options
	PKCE         bool   // Enable PKCE (recommended for mobile apps)
	ResponseType string // OAuth response type (default: "code")
	ResponseMode string // Response mode (query/form_post)
	Prompt       string // Auth prompt (login/consent/etc)
	AccessType   string // Access type (offline for refresh tokens)

	// User Sign Up Control
	DisableImplicitSignUp bool // Require explicit sign-up
	DisableSignUp         bool // Disable sign-up entirely
	OverrideUserInfo      bool // Update user info on each sign-in

	// Custom Functions (optional)
	GetUserInfo func(*Tokens) (*User, error)           // Custom user info fetcher
	MapProfile  func(map[string]interface{}) (*User, error) // Profile mapper
}

// Tokens represents OAuth token response.
//
// This struct holds the tokens returned by the provider after successful
// authorization code exchange. It's used for custom user info fetching.
type Tokens struct {
	AccessToken  string                 // OAuth access token
	RefreshToken string                 // OAuth refresh token
	ExpiresAt    time.Time              // Token expiration time
	Scopes       []string               // Granted scopes
	Raw          map[string]interface{} // Provider-specific fields
}
